/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaSelector: typeof import('./src/components/AreaSelector.vue')['default']
    copy: typeof import('./src/components/CustomUploader copy.vue')['default']
    CustomUploader: typeof import('./src/components/CustomUploader.vue')['default']
    DocViewer: typeof import('./src/components/DocViewer.vue')['default']
    ExcelViewer: typeof import('./src/components/ExcelViewer.vue')['default']
    FieldUploader: typeof import('./src/components/FieldUploader.vue')['default']
    FieldUploaderDemo: typeof import('./src/components/FieldUploaderDemo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageIcon: typeof import('./src/components/ImageIcon.vue')['default']
    MobileTable: typeof import('./src/components/MobileTable.vue')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
